const TRAITS={hustler:{name:"Hustler",skill:"hustle"},techie:{name:"Techie",skill:"coding"},social:{name:"People Person",skill:"charisma"},book:{name:"Book Smart",skill:"academics"}};
const CAREERS=[{id:"tech",name:"Tech",skill:"coding",levels:[["Intern",4500,1],["Developer",9000,2],["Senior Developer",18000,4],["Tech Lead",35000,6],["Founder/CTO",65000,8]]},{id:"bank",name:"Banking",skill:"charisma",levels:[["Teller",4000,1],["Officer",7500,2],["Manager",16000,4],["Regional Head",32000,6],["MD",60000,8]]},{id:"trade",name:"Trading",skill:"hustle",levels:[["Shop Assistant",3000,1],["Seller",6500,2],["Distributor",14000,4],["Importer",30000,6],["Market Boss",55000,8]]}];
const PLACES={nsukka:{name:"Nsukka",fare:0},newhaven:{name:"New Haven",fare:2500},independence:{name:"Independence Layout",fare:2800},ogbete:{name:"Ogbete",fare:2300},nike:{name:"Nike",fare:3000}};
const HOMES=[{name:"Campus Lodge",rent:2500},{name:"Nsukka Self-contain",rent:6000},{name:"Enugu Flat",rent:22000},{name:"GRA Duplex",rent:180000}];
let s=JSON.parse(localStorage.getItem("enuguLifeV2"))||{cash:15000,day:1,week:1,place:"nsukka",origin:null,trait:"hustler",career:null,careerLevel:0,home:0,debt:0,needs:{hunger:82,energy:86,fun:70,social:65,hygiene:88},skills:{hustle:1,coding:1,charisma:1,academics:1},rep:0,logs:[]};
const $=x=>document.getElementById(x);function clamp(n){return Math.max(0,Math.min(100,n))}function log(t){s.logs.unshift("Day "+s.day+" — "+t);s.logs=s.logs.slice(0,8)}
function tick(){s.day++;for(const k in s.needs)s.needs[k]=clamp(s.needs[k]-Math.floor(Math.random()*7+3));if(s.day%7===0){s.week++;let rent=HOMES[s.home].rent;s.cash-=rent;log("Weekly rent: ₦"+rent.toLocaleString());if(s.debt>0){let p=Math.min(10000,s.debt);s.cash-=p;s.debt-=p;log("Loan repayment: ₦"+p.toLocaleString())}}if(s.cash<0){s.debt+=Math.abs(s.cash);s.cash=0;log("You fell short. Debt increased.")}}
function origin(){if(s.origin)return;let rich=Math.random()<.12;s.origin=rich?"connected":"grind";if(rich){s.cash=350000;s.home=2;s.rep=8;log("You were born Connected: family support, Enugu flat and a head start.")}else{s.cash=30000;s.debt=60000;s.skills.hustle=2;log("You drew the Grind start: ₦60k debt, but Hustle starts stronger.")}save()}
function eat(){if(s.cash<700)return log("Not enough money for food."),save();s.cash-=700;s.needs.hunger=clamp(s.needs.hunger+28);log("You ate a proper Enugu meal.");tick();save()}
function sleep(){s.needs.energy=100;s.needs.hygiene=clamp(s.needs.hygiene-8);log("You slept and recovered.");tick();save()}
function shower(){s.needs.hygiene=100;log("Freshened up.");tick();save()}
function train(k){s.skills[k]=Math.min(10,s.skills[k]+1);s.needs.energy=clamp(s.needs.energy-15);log("Trained "+k+" to level "+s.skills[k]+".");tick();save()}
function applyCareer(id){let c=CAREERS.find(x=>x.id===id);s.career=id;s.careerLevel=0;log("You joined "+c.name+" as "+c.levels[0][0]+".");save()}
function work(){if(!s.career)return log("Choose a career first."),save();let c=CAREERS.find(x=>x.id===s.career),l=c.levels[s.careerLevel],mood=Object.values(s.needs).reduce((a,b)=>a+b,0)/5;if(s.needs.energy<20||s.needs.hunger<20)return log("Your needs are too low to work."),save();let pay=Math.round(l[1]*(mood>70?1.1:1));s.cash+=pay;s.needs.energy=clamp(s.needs.energy-22);s.needs.hunger=clamp(s.needs.hunger-18);s.rep++;log("Worked as "+l[0]+" and earned ₦"+pay.toLocaleString()+".");if(s.skills[c.skill]>=l[2]+2&&s.careerLevel<c.levels.length-1){s.careerLevel++;log("PROMOTED to "+c.levels[s.careerLevel][0]+"!")}tick();save()}
function gig(){let pay=1200+s.skills.hustle*550;s.cash+=pay;s.needs.energy=clamp(s.needs.energy-12);log("Side hustle paid ₦"+pay.toLocaleString()+".");tick();save()}
function travel(id){let p=PLACES[id];if(s.cash<p.fare)return log("You cannot afford the trip."),save();s.cash-=p.fare;s.place=id;log("Travelled to "+p.name+".");tick();save()}
function buyHome(i){let h=HOMES[i];let deposit=h.rent*4;if(s.cash<deposit)return log("You need ₦"+deposit.toLocaleString()+" for the move-in deposit."),save();s.cash-=deposit;s.home=i;log("Moved into "+h.name+".");save()}
function save(){localStorage.setItem("enuguLifeV2",JSON.stringify(s));render()}
function render(){if(!$("dashboard"))return;$("cash").textContent=s.cash.toLocaleString();$("meta").textContent="Day "+s.day+" • Week "+s.week+" • "+PLACES[s.place].name;$("origin").textContent=s.origin?(s.origin==="connected"?"Connected Start":"Grind Start"):"Unrevealed";$("home").textContent=HOMES[s.home].name;$("debt").textContent="₦"+s.debt.toLocaleString();$("rep").textContent=s.rep;["hunger","energy","fun","social","hygiene"].forEach(k=>$(k).textContent=s.needs[k]);$("skills").innerHTML=Object.entries(s.skills).map(([k,v])=>'<button onclick="train(\''+k+'\')">'+k+" Lv."+v+"</button>").join("");$("careers").innerHTML=CAREERS.map(c=>'<button onclick="applyCareer(\''+c.id+'\')">'+c.name+"</button>").join("");$("places").innerHTML=Object.entries(PLACES).map(([k,p])=>'<button onclick="travel(\''+k+'\')">'+p.name+(p.fare?" • ₦"+p.fare.toLocaleString():"")+"</button>").join("");$("homes").innerHTML=HOMES.map((h,i)=>'<button onclick="buyHome('+i+')">'+h.name+" • ₦"+h.rent.toLocaleString()+"/wk</button>").join("");$("log").innerHTML=s.logs.length?s.logs.join("<br>"):"Your story is waiting.";let c=s.career&&CAREERS.find(x=>x.id===s.career);$("job").textContent=c?c.name+" • "+c.levels[s.careerLevel][0]:"Unemployed"}render();